## GITHUB ACTION FOR R PACKAGE
## Build, check, test, code coverage
## Required secrets
## CODECOV_TOKEN

name: r-cmd-check
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  linux:
    name: ubuntu
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        r: [4.0,4.4]
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{matrix.r}}

      - name: Install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype6-dev libcurl4-openssl-dev libssl-dev libxml2-dev libnlopt-dev

      - name: Check R installation
        run: Rscript -e "print('R installation works!')"

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::rcmdcheck
            any::pkgdepends
            any::covr
          needs: check

      - name: R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"warning"'
          check-dir: '"check"'

      - name: Code coverage
        if: matrix.r == '4.4'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: Rscript -e 'covr::codecov(token="${{ secrets.CODECOV_TOKEN }}",quiet=FALSE)'

  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        r: [4.0,4.4]
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{matrix.r}}

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::rcmdcheck
            any::pkgdepends
            any::covr
          needs: check

      - name: R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"warning"'
          check-dir: '"check"'
